name: 4 Archive Unit Test Reports

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  unit-testing:
    name: Run & Archive Mocha Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Run Unit Tests
        run: echo "npm test"

      - name: Archive Test Result
        uses: actions/upload-artifact@v7.0.1
        with:
          name: Mocha-Test-Result
          path: test-results.xml


  code-coverage:
      name: Code Coverage
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v4
  
        - name: Setup Node.js 18
          uses: actions/setup-node@v6.5.0
          with:
            node-version: 24
  
        - name: Install Dependencies
          run: npm install
  
        - name: Generate Coverage Report
          run: npm run coverage
  
        - name: Archive Coverage Report
          uses: actions/upload-artifact@v7.0.1
          with:
            name: Code-Coverage-Result
            path: coverage
        retention-days: 5
